[package]
name = "poly"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
env_logger = "0.10.0"
num = "0.4.0"
smallvec = "1.10.0"

[dev-dependencies]
rstest = "0.15.0"
